name: 05-dev-prod-environments

on:
  workflow_dispatch

jobs:
  train-model:
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: install az ml extension
      run: az extension add -n ml -y
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Connect/Create Azure Machine Learning Workspace
      id: aml_workspace
      uses: Azure/aml-workspace@v1
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Trigger Azure Machine Learning job
      id: aml_trainmodel
      run: |
        cd src
        az ml job create --file job.yml --resource-group rg-dev-mlops --workspace-name mlw-dev-mlops
    - name: Register model
      id: aml_registermodel
      uses: Azure/aml-registermodel@v1
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          run_id:  ${{ steps.aml_trainmodel.outputs.run_id }}
          experiment_name: ${{ steps.aml_run.outputs.experiment_name }}
          
