# This is a basic workflow to help you get started with Actions

name: List models in prod

on:
  workflow_dispatch

jobs:
  train-model:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: install az ml extension
      run: az extension add -n ml -y
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure Machine Learning job
      id: aml_trainmodel
      run: |
        cd src 
        az ml model list --resource-group rg-dev-mlops --workspace-name mlw-dev-mlops
